name: Publish

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  ###################################################
  # BUILD
  ###################################################

  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Git tags'
        run: git fetch --tags
        shell: bash

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3

      - name: Publish
        shell: bash
        run: |
          dotnet tool restore
          dotnet cake --target="publish" \
            --nuget-key="${{secrets.NUGET_API_KEY}}" \
            --github-key="${{secrets.GITHUB_TOKEN}}"